name: Test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11]
        jna: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run Gradle tests with JNA
        if: ${{ matrix.jna }}
        run: ./gradlew test -PnoJnaInTests
      - name: Run Gradle tests
        if: ${{ !matrix.jna }}
        run: ./gradlew test -PnoJnaInTests
      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ${{ matrix.os }}-java${{ matrix.jdk }}-test-report
          path: build/reports
